imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ICAPWebBiblioBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# SSO Configuration
#be_simple_sso_auth:
#    admin_sso:
#        protocol:
#            id: cas
#            version: 2
#        server:
#            id: cas
#            login_url: https://cas.univ-lyon1.fr:443/cas/login
#            logout_url: https://cas.univ-lyon1.fr:443/cas/logout
#            validation_url: https://cas.univ-lyon1.fr:443/cas/serviceValidate

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

ornicar_gravatar:
    rating: g
    size: 40
    default: mm

sonata_admin:
    title: WebBiblio Admin
    templates:
        # default global templates
        layout: SonataAdminBundle::standard_layout.html.twig
        ajax: SonataAdminBundle::ajax_layout.html.twig
        # default actions templates, should extend a global templates
        list: SonataAdminBundle:CRUD:list.html.twig
        show: SonataAdminBundle:CRUD:show.html.twig
        edit: SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
parameters:
    sonata.user.admin.user.class:   Application\Sonata\UserBundle\Admin\UserAdmin
    sonata.user.admin.group.class:  Application\Sonata\UserBundle\Admin\GroupAdmin
