security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        #Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        #in_memory:
        #    memory:
        #        users:
        #            - {name: vincent.saisset@gmail.com, password: vaince, roles: [ 'ROLE_USER' ] }
        #            - {name: ptsavdar@gmail.com, password: panos, roles: [ 'ROLE_USER' ] }
        #            - {name: vincent.saisset, password: 123456, roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /web-biblio
            logout:       
                target: /login
            anonymous:    true

        #login_firewall:
        #    pattern:    ^/web-biblio/login$
        #    anonymous:  ~
        #secured_area:
        #    pattern:    ^/
        #    anonymous: ~
        #    form_login:
        #        login_path:  web_biblio_not_logged
        #        check_path:  web_biblio_connect
        #        failure_path: web_biblio_login
        #    logout:
        #        path:   web_biblio_disconnect
        #        target: web_biblio_login

    access_control:
        #- { path: ^/web-biblio/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }