<?php

namespace ICAP\Bundle\WebBiblioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	const QUERY_PROPERTY = "q";
    
    public function customSearch($params)
    {
        $qb = $this->getTagsQueryBuilder();
        foreach ($params as $key => $value) {
            if($key == self::QUERY_PROPERTY){
                $qb
                    ->andWhere('tag.name LIKE :value')
                    ->setParameter('value', '%'.$value.'%')
                ;
            }
        }

        return $qb->getQuery()->getResult();
    }

	public function getTagsQueryBuilder()
    {
        return $this
            ->createQueryBuilder('tag')
            ->orderBy('tag.name', 'ASC')
        ;
    }
}
