<?php

namespace ICAP\Bundle\WebBiblioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebLinkRepository extends EntityRepository
{
    const TAGNAMES_PROPERTY = "tagnames";
    const USERNAME_PROPERTY = "usernames";

    public function extractQueryBuilder($params)
    {
        $qb = $this->getPublishedWebLinksQueryBuilder();
        foreach ($params as $key => $value) {
            if($key == self::TAGNAMES_PROPERTY){
                $qb
                    ->leftJoin('weblink.tags', 'tag')
                    ->andWhere(
                        $qb
                            ->expr()
                            ->in('tag.name', "'".$value."'")
                    )
                ;
            }else if($key == self::USERNAME_PROPERTY){
                $qb
                    ->andWhere(
                        $qb
                            ->expr()
                            ->in('weblink.username', "'".$value."'")
                    )
                ;
            } 
        }

        return $qb;
    }

    /**
     * extractQuery
     *
     * @param array $params
     * @return Query
     */
    public function extractQuery($params)
    {
        $qb = $this->extractQueryBuilder($params);

        return is_null($qb) ? $qb : $qb->getQuery();
    }

    /**
     * extract
     *
     * @param array $params
     * @return DoctrineCollection
     */
    public function extract($params)
    {
        $q = $this->extractQuery($params);
        
        return is_null($q) ? array() : $q->getResult();
    }

    public function getPublishedWebLinksQueryBuilder()
    {
        return $this
            ->createQueryBuilder('weblink')
            ->andWhere('weblink.published = :value')
            ->setParameter('value', true)
            ->orderBy('weblink.url', 'ASC')
        ;
    }

    public function getPublishedWebLinksQuery()
    {
        return $this->getPublishedWebLinksQueryBuilder()->getQuery();
    }

    public function getPublishedWebLinks()
    {
        return $this->getPublishedWebLinksQuery()->getResults();
    }

    public function getWebLinksQueryBuilderForUsername($username)
    {
        return $this
            ->createQueryBuilder('webLink')
            ->andWhere('webLink.username = :username')
            ->setParameter('username', $username)
            ->orderBy('webLink.id','ASC')
        ;
    }

    public function getWebLinkIndexInList($username, $weblinkId)
    {
        $q = $this
            ->getWebLinksQueryBuilderForUsername($username)
            ->select('count(webLink.id) as total')
            ->andWhere('webLink.id <= :weblinkId')
            ->setParameter('weblinkId', $weblinkId)
            
        ;

        return $q->getQuery()->getSingleScalarResult();
    }
}
