<?php

namespace ICAP\Bundle\WebBiblioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebLinkRepository extends EntityRepository
{
    const TAGNAMES_PROPERTY = "tagNames";
    const USERNAME_PROPERTY = "username";
    const URL_PROPERTY = "url";

    public function customSearch($params)
    {
        $qb = $this.getPublishedWebLinksQueryBuilder();
        foreach ($params as $key => $value) {
            if($key == TAGNAMES_PROPERTY){
                $qb
                    ->leftJoin('weblink.tags', 'tag')
                    ->andWhere(
                        $qb
                            ->expr()
                            ->in('tag.name', implode(",", $value)
                    )
                ;
            }else if($key == USERNAME_PROPERTY){
                $qb
                    ->andWhere(
                        $qb
                            ->expr()
                            ->in('weblink.username', implode(",", $value)
                    )
                ;
            } else if(isValidProperty($key)){
                $qb
                    ->andWhere('weblink.:key = ":value"')
                    ->setParameter('key', $key)
                    ->setParameter('value', $value)
                ;
            }
        }

        return $qb->getQuery()->getResult();
    }

    public function getPublishedWebLinksQueryBuilder()
    {
        return $this
            ->createQueryBuilder('weblink')
            ->andWhere('weblink.published = ":value"')
            ->setParameter('value', true)
            ->orderBy('weblink.url', 'ASC')
        ;
    }

    public function getPublishedebLinksQuery()
    {
        return $this->getPublishedWebLinksQueryBuilder()->getQuery();

    }

    public function getPublishedWebLinks()
    {
        return $this->getPublishedWebLinksQuery()->getResults();

    }

    private function isValidProperty($param)
    {
        if($param == URL_PROPERTY){
            return true;
        }

        return false;
    }

}
