idci_exporter:
    entities
        entity_reference:
            class: "ICAP\\Bundle\\WebBiblioBundle\\Entity\\WebLink"
            formats:
                jsonp:
                    template_name_format: "export.json.twig"