services: 
    icap_webbiblio.manager: 
        class: ICAP\Bundle\WebBiblioBundle\Service\Manager
        arguments: [@doctrine.orm.entity_manager, @logger, @security.acl.provider, @security.context]

    icap_webbiblio.type.icap_bundle_webbibliobundle_tagstype:
        class: ICAP\Bundle\WebBiblioBundle\Form\TagsType
        arguments: []
        tags:
            - { name: form.type, alias: icap_bundle_webbibliobundle_tagstype }

